import { Quest } from '../domain/Quest.js';

// Authored opportunities use Brightbell's enemy, NPC, and challenge identities
// where they exist. Glasswake's fourth Area extends the same small objective
// vocabulary using the bundled Mirrorfen content.
const TEMPLATES = [
  {
    id: 'guild-field-check',
    title: 'Guild Field Check',
    description: 'Complete a Hunt to show the guild you are ready for work beyond Town.',
    areaNumber: 1,
    townId: 'area-1-town',
    objectives: [{ id: 'complete-hunt', type: 'hunt', count: 1 }],
    reward: { gold: 18, experience: 45 },
  },
  {
    id: 'welcome-to-bellbloom',
    title: 'Welcome to Bellbloom',
    description: 'Check in with a local before you follow the Brightbell Road.',
    areaNumber: 1,
    townId: 'area-1-town',
    npcId: 'area-1-shopkeeper',
    objectives: [{ id: 'speak-with-the-guild', type: 'speak', targetId: 'area-1-shopkeeper', targetLabel: 'the Bellbloom shopkeeper' }],
    reward: { gold: 12, experience: 35 },
  },
  {
    id: 'bouncebud-roundup',
    title: 'Bouncebud Roundup',
    description: 'Thin the restless slime population along the flower-bell road.',
    areaNumber: 1,
    townId: 'area-1-town',
    objectives: [{ id: 'clear-bouncebuds', type: 'kill', targetId: 'bouncebud-slime', targetLabel: 'Bouncebud Slimes', count: 3 }],
    reward: { gold: 22, experience: 55 },
  },
  {
    id: 'ribbon-road-patrol',
    title: 'Ribbon Road Patrol',
    description: 'Drive off the boars crowding the courier path.',
    areaNumber: 1,
    townId: 'area-1-town',
    objectives: [{ id: 'clear-ribbon-boars', type: 'kill', targetId: 'ribbon-boar', targetLabel: 'Ribbon Boars', count: 2 }],
    reward: { gold: 24, experience: 60 },
  },
  {
    id: 'orchard-patrol',
    title: 'Orchard Patrol',
    description: 'Take the warmglass orchard path and report what has changed.',
    areaNumber: 2,
    townId: 'area-2-town',
    objectives: [{ id: 'walk-the-orchard', type: 'adventure', count: 2 }],
    reward: { gold: 38, experience: 90 },
  },
  {
    id: 'quiet-the-hornets',
    title: 'Quiet the Hornets',
    description: 'Clear emberwing hornets from the orchard workers’ route.',
    areaNumber: 2,
    townId: 'area-2-town',
    objectives: [{ id: 'clear-hornets', type: 'kill', targetId: 'emberwing-hornet', targetLabel: 'Emberwing Hornets', count: 3 }],
    reward: { gold: 42, experience: 100 },
  },
  {
    id: 'warm-road-check-in',
    title: 'Warm Road Check-in',
    description: 'Speak with the waystation guide about the orchard’s signal.',
    areaNumber: 2,
    townId: 'area-2-town',
    npcId: 'area-2-guide',
    objectives: [{ id: 'ask-the-guide', type: 'speak', targetId: 'area-2-guide', targetLabel: 'the waystation guide' }],
    reward: { gold: 20, experience: 52 },
  },
  {
    id: 'procession-through-fire',
    title: 'Procession Through Fire',
    description: 'Help the orchard party escort its travelers through the Emberglass Procession.',
    areaNumber: 2,
    townId: 'area-2-town',
    objectives: [{ id: 'clear-the-procession', type: 'boss', targetId: 'emberglass-procession', targetLabel: 'Emberglass Procession' }],
    reward: { gold: 64, experience: 150 },
  },
  {
    id: 'meet-kitewatch',
    title: 'Meet Kitewatch',
    description: 'Ask the signalers what the summit bell has been answering.',
    areaNumber: 3,
    townId: 'area-3-town',
    npcId: 'sera-kite',
    objectives: [{ id: 'find-sera', type: 'speak', targetId: 'sera-kite', targetLabel: 'Sera Kite' }],
    reward: { gold: 34, experience: 82 },
  },
  {
    id: 'rook-remembers',
    title: 'Rook Remembers',
    description: 'Hear Rook Gale’s account of the last time the summit signal rang twice.',
    areaNumber: 3,
    townId: 'area-3-town',
    npcId: 'rook-gale',
    objectives: [{ id: 'find-rook', type: 'speak', targetId: 'rook-gale', targetLabel: 'Rook Gale' }],
    reward: { gold: 36, experience: 86 },
  },
  {
    id: 'starhorn-count',
    title: 'Starhorn Count',
    description: 'Keep the highland trail open by dispersing its restless spirits.',
    areaNumber: 3,
    townId: 'area-3-town',
    objectives: [{ id: 'disperse-starhorns', type: 'kill', targetId: 'starhorn-spirit', targetLabel: 'Starhorn Spirits', count: 3 }],
    reward: { gold: 72, experience: 160 },
  },
  {
    id: 'restore-the-duet',
    title: 'Restore the Duet',
    description: 'Reach the summit bell with another Weaver and restore its answering note.',
    areaNumber: 3,
    townId: 'area-3-town',
    objectives: [{ id: 'ring-the-summit-bell', type: 'boss', targetId: 'kitewind-summit', targetLabel: 'Kitewind Summit' }],
    reward: { gold: 105, experience: 230 },
  },
  {
    id: 'mirrorfen-scout-report',
    title: 'Mirrorfen Scout Report',
    description: 'Ask the waystation scout which reflections are following the party.',
    areaNumber: 4,
    townId: 'area-4-town',
    npcId: 'mirrorfen-guide',
    objectives: [{ id: 'hear-the-scout', type: 'speak', targetId: 'mirrorfen-guide', targetLabel: 'the Mirrorfen scout' }],
    reward: { gold: 54, experience: 126 },
  },
  {
    id: 'glass-skulker-roundup',
    title: 'Glass Skulker Roundup',
    description: 'Drive the skulkers away from the Mirrorfen crossing.',
    areaNumber: 4,
    townId: 'area-4-town',
    objectives: [{ id: 'drive-off-skulkers', type: 'kill', targetId: 'glass-skulker', targetLabel: 'Glass Skulkers', count: 3 }],
    reward: { gold: 104, experience: 238 },
  },
  {
    id: 'walk-the-reflection-line',
    title: 'Walk the Reflection Line',
    description: 'Cross the Mirrorfen and keep an ally in reach when the reflections mark them.',
    areaNumber: 4,
    townId: 'area-4-town',
    objectives: [{ id: 'cross-mirrorfen', type: 'adventure', count: 2 }],
    reward: { gold: 86, experience: 205 },
  },
  {
    id: 'no-weaver-left-reflected',
    title: 'No Weaver Left Reflected',
    description: 'Break through the Mirrorfen Descent together and leave no reflection behind.',
    areaNumber: 4,
    townId: 'area-4-town',
    objectives: [{ id: 'clear-mirrorfen-descent', type: 'boss', targetId: 'mirrorfen-descent', targetLabel: 'Mirrorfen Descent' }],
    reward: { gold: 168, experience: 360 },
  },
];

export const QUEST_CATALOG = Object.freeze(TEMPLATES.map((definition) => new Quest(definition)));
